// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CLGT.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace CLGT
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HandReq : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int platform { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int product { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int version { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public string device { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public int channel { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public string country { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public string language { get; set; } = "";

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(platform != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(platform);
            }
            if(product != 0)
            {
                writer.WriteTag(16);
                writer.WriteInt32(product);
            }
            if(version != 0)
            {
                writer.WriteTag(24);
                writer.WriteInt32(version);
            }
            if(device != "")
            {
                writer.WriteTag(34);
                writer.WriteString(device);
            }
            if(channel != 0)
            {
                writer.WriteTag(40);
                writer.WriteInt32(channel);
            }
            if(country != "")
            {
                writer.WriteTag(50);
                writer.WriteString(country);
            }
            if(language != "")
            {
                writer.WriteTag(58);
                writer.WriteString(language);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            platform = 0;

            product = 0;

            version = 0;

            device = "";

            channel = 0;

            country = "";

            language = "";

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            platform = reader.ReadInt32();
                        }
                        break;
                    case 16:
                        {
                            product = reader.ReadInt32();
                        }
                        break;
                    case 24:
                        {
                            version = reader.ReadInt32();
                        }
                        break;
                    case 34:
                        {
                            device = reader.ReadString();
                        }
                        break;
                    case 40:
                        {
                            channel = reader.ReadInt32();
                        }
                        break;
                    case 50:
                        {
                            country = reader.ReadString();
                        }
                        break;
                    case 58:
                        {
                            language = reader.ReadString();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
        [global::ProtoBuf.ProtoContract()]
        public enum PlatformType
        {
            Unknown = 0,
            IOS = 1,
            ANDROID = 2,
            WINDOWS = 3,
            LINUX = 4,
            MAC = 5,
            WebGL = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HandAck : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int errcode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int payload { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] random_key { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public global::System.Collections.Generic.List<int> random_key_arr { get; private set; } = new global::System.Collections.Generic.List<int>();

        [global::ProtoBuf.ProtoMember(5)]
        public string session_guid { get; set; } = "";

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(errcode != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(errcode);
            }
            if(payload != 0)
            {
                writer.WriteTag(16);
                writer.WriteInt32(payload);
            }
            if(random_key != null)
            {
                writer.WriteTag(26);
                writer.WriteBytes(random_key);
            }
            writer.WriteTag(34);
            writer.WriteRepeated((listw) => {
                foreach(var itor in random_key_arr)
                {
                    listw.WriteInt32(itor);
                }
            });
            if(session_guid != "")
            {
                writer.WriteTag(42);
                writer.WriteString(session_guid);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            errcode = 0;

            payload = 0;

            random_key = null;

            random_key_arr.Clear();

            session_guid = "";

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            errcode = reader.ReadInt32();
                        }
                        break;
                    case 16:
                        {
                            payload = reader.ReadInt32();
                        }
                        break;
                    case 26:
                        {
                            random_key = reader.ReadBytes();
                        }
                        break;
                    case 34:
                        {
                            reader.ReadRepeated((listr) => {
                                var o = listr.ReadInt32();
                                random_key_arr.Add(o);
                            });
                        }
                        break;
                    case 42:
                        {
                            session_guid = reader.ReadString();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DisconnectNtf : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public string errmessage { get; set; } = "";

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(code != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(code);
            }
            if(errmessage != "")
            {
                writer.WriteTag(18);
                writer.WriteString(errmessage);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            code = 0;

            errmessage = "";

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            code = reader.ReadInt32();
                        }
                        break;
                    case 18:
                        {
                            errmessage = reader.ReadString();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemInfo : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int item_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int item_sub_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long item_count { get; set; }

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(item_id != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(item_id);
            }
            if(item_sub_id != 0)
            {
                writer.WriteTag(16);
                writer.WriteInt32(item_sub_id);
            }
            if(item_count != 0)
            {
                writer.WriteTag(24);
                writer.WriteInt64(item_count);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            item_id = 0;

            item_sub_id = 0;

            item_count = 0;

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            item_id = reader.ReadInt32();
                        }
                        break;
                    case 16:
                        {
                            item_sub_id = reader.ReadInt32();
                        }
                        break;
                    case 24:
                        {
                            item_count = reader.ReadInt64();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginReq : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int login_type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public string token { get; set; } = "";

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(login_type != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(login_type);
            }
            if(token != "")
            {
                writer.WriteTag(18);
                writer.WriteString(token);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            login_type = 0;

            token = "";

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            login_type = reader.ReadInt32();
                        }
                        break;
                    case 18:
                        {
                            token = reader.ReadString();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginAck : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int errcode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int user_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public string nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public bool nickname_mdf { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int gender { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int head { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int head_frame { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int level { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public long level_exp { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int vip_level { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public long vip_level_exp { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public string phone { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13)]
        public long diamond { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public long currency { get; set; }

        [global::ProtoBuf.ProtoMember(17, TypeName = "CLGT.ItemInfo")]
        public global::System.Collections.Generic.List<ItemInfo> items { get; private set; } = new global::System.Collections.Generic.List<ItemInfo>();

        [global::ProtoBuf.ProtoMember(18, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint server_timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public bool has_unread_mail { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public uint month_card_expire_time { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public bool month_card_has_fetched { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public string client_config_md5 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(29)]
        public long max_gun_value { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public string time_string { get; set; } = "";

        [global::ProtoBuf.ProtoMember(31)]
        public bool bank_password_flag { get; set; }

        [global::ProtoBuf.ProtoMember(41)]
        public long bank_currency { get; set; }

        [global::ProtoBuf.ProtoMember(42)]
        public string last_game_appid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(43)]
        public string head_url { get; set; } = "";

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(errcode != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(errcode);
            }
            if(user_id != 0)
            {
                writer.WriteTag(16);
                writer.WriteInt32(user_id);
            }
            if(nickname != "")
            {
                writer.WriteTag(26);
                writer.WriteString(nickname);
            }
            if(nickname_mdf != false)
            {
                writer.WriteTag(32);
                writer.WriteBool(nickname_mdf);
            }
            if(gender != 0)
            {
                writer.WriteTag(40);
                writer.WriteInt32(gender);
            }
            if(head != 0)
            {
                writer.WriteTag(48);
                writer.WriteInt32(head);
            }
            if(head_frame != 0)
            {
                writer.WriteTag(56);
                writer.WriteInt32(head_frame);
            }
            if(level != 0)
            {
                writer.WriteTag(64);
                writer.WriteInt32(level);
            }
            if(level_exp != 0)
            {
                writer.WriteTag(72);
                writer.WriteInt64(level_exp);
            }
            if(vip_level != 0)
            {
                writer.WriteTag(80);
                writer.WriteInt32(vip_level);
            }
            if(vip_level_exp != 0)
            {
                writer.WriteTag(88);
                writer.WriteInt64(vip_level_exp);
            }
            if(phone != "")
            {
                writer.WriteTag(98);
                writer.WriteString(phone);
            }
            if(diamond != 0)
            {
                writer.WriteTag(104);
                writer.WriteInt64(diamond);
            }
            if(currency != 0)
            {
                writer.WriteTag(112);
                writer.WriteInt64(currency);
            }
            foreach(var itor in items)
            {
                writer.WriteTag(138);
                writer.WriteMessage((msrw) => {
                    if(itor != null)
                    {
                        itor.Encode(msrw);
                    }
                });
            }
            if(server_timestamp != 0)
            {
                writer.WriteTag(149);
                writer.WriteFixed32(server_timestamp);
            }
            if(has_unread_mail != false)
            {
                writer.WriteTag(160);
                writer.WriteBool(has_unread_mail);
            }
            if(month_card_expire_time != 0)
            {
                writer.WriteTag(184);
                writer.WriteDouble(month_card_expire_time);
            }
            if(month_card_has_fetched != false)
            {
                writer.WriteTag(192);
                writer.WriteBool(month_card_has_fetched);
            }
            if(client_config_md5 != "")
            {
                writer.WriteTag(226);
                writer.WriteString(client_config_md5);
            }
            if(max_gun_value != 0)
            {
                writer.WriteTag(232);
                writer.WriteInt64(max_gun_value);
            }
            if(time_string != "")
            {
                writer.WriteTag(242);
                writer.WriteString(time_string);
            }
            if(bank_password_flag != false)
            {
                writer.WriteTag(248);
                writer.WriteBool(bank_password_flag);
            }
            if(bank_currency != 0)
            {
                writer.WriteTag(328);
                writer.WriteInt64(bank_currency);
            }
            if(last_game_appid != "")
            {
                writer.WriteTag(338);
                writer.WriteString(last_game_appid);
            }
            if(head_url != "")
            {
                writer.WriteTag(346);
                writer.WriteString(head_url);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            errcode = 0;

            user_id = 0;

            nickname = "";

            nickname_mdf = false;

            gender = 0;

            head = 0;

            head_frame = 0;

            level = 0;

            level_exp = 0;

            vip_level = 0;

            vip_level_exp = 0;

            phone = "";

            diamond = 0;

            currency = 0;

            items.Clear();

            server_timestamp = 0;

            has_unread_mail = false;

            month_card_expire_time = 0;

            month_card_has_fetched = false;

            client_config_md5 = "";

            max_gun_value = 0;

            time_string = "";

            bank_password_flag = false;

            bank_currency = 0;

            last_game_appid = "";

            head_url = "";

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            errcode = reader.ReadInt32();
                        }
                        break;
                    case 16:
                        {
                            user_id = reader.ReadInt32();
                        }
                        break;
                    case 26:
                        {
                            nickname = reader.ReadString();
                        }
                        break;
                    case 32:
                        {
                            nickname_mdf = reader.ReadBool();
                        }
                        break;
                    case 40:
                        {
                            gender = reader.ReadInt32();
                        }
                        break;
                    case 48:
                        {
                            head = reader.ReadInt32();
                        }
                        break;
                    case 56:
                        {
                            head_frame = reader.ReadInt32();
                        }
                        break;
                    case 64:
                        {
                            level = reader.ReadInt32();
                        }
                        break;
                    case 72:
                        {
                            level_exp = reader.ReadInt64();
                        }
                        break;
                    case 80:
                        {
                            vip_level = reader.ReadInt32();
                        }
                        break;
                    case 88:
                        {
                            vip_level_exp = reader.ReadInt64();
                        }
                        break;
                    case 98:
                        {
                            phone = reader.ReadString();
                        }
                        break;
                    case 104:
                        {
                            diamond = reader.ReadInt64();
                        }
                        break;
                    case 112:
                        {
                            currency = reader.ReadInt64();
                        }
                        break;
                    case 138:
                        {
                            CLGT.ItemInfo o = null;
                            reader.ReadMessage((msgr) => {
                                o = new CLGT.ItemInfo();
                                o.Decode(msgr);
                            });
                            items.Add(o);
                        }
                        break;
                    case 149:
                        {
                            server_timestamp = reader.ReadFixed32();
                        }
                        break;
                    case 160:
                        {
                            has_unread_mail = reader.ReadBool();
                        }
                        break;
                    case 184:
                        {
                            month_card_expire_time = reader.ReadUInt32();
                        }
                        break;
                    case 192:
                        {
                            month_card_has_fetched = reader.ReadBool();
                        }
                        break;
                    case 226:
                        {
                            client_config_md5 = reader.ReadString();
                        }
                        break;
                    case 232:
                        {
                            max_gun_value = reader.ReadInt64();
                        }
                        break;
                    case 242:
                        {
                            time_string = reader.ReadString();
                        }
                        break;
                    case 248:
                        {
                            bank_password_flag = reader.ReadBool();
                        }
                        break;
                    case 328:
                        {
                            bank_currency = reader.ReadInt64();
                        }
                        break;
                    case 338:
                        {
                            last_game_appid = reader.ReadString();
                        }
                        break;
                    case 346:
                        {
                            head_url = reader.ReadString();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccessServiceReq : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public string server_name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int action { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public string app_id { get; set; } = "";

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(server_name != "")
            {
                writer.WriteTag(10);
                writer.WriteString(server_name);
            }
            if(action != 0)
            {
                writer.WriteTag(16);
                writer.WriteInt32(action);
            }
            if(app_id != "")
            {
                writer.WriteTag(26);
                writer.WriteString(app_id);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            server_name = "";

            action = 0;

            app_id = "";

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 10:
                        {
                            server_name = reader.ReadString();
                        }
                        break;
                    case 16:
                        {
                            action = reader.ReadInt32();
                        }
                        break;
                    case 26:
                        {
                            app_id = reader.ReadString();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccessServiceAck : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int errcode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public string errmessage { get; set; } = "";

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(errcode != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(errcode);
            }
            if(errmessage != "")
            {
                writer.WriteTag(18);
                writer.WriteString(errmessage);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            errcode = 0;

            errmessage = "";

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            errcode = reader.ReadInt32();
                        }
                        break;
                    case 18:
                        {
                            errmessage = reader.ReadString();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeepAliveReq : AssemblyCommon.IProtoMessage
    {
        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeepAliveAck : AssemblyCommon.IProtoMessage
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int errcode { get; set; }

        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
            if(errcode != 0)
            {
                writer.WriteTag(8);
                writer.WriteInt32(errcode);
            }
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            errcode = 0;

            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    case 8:
                        {
                            errcode = reader.ReadInt32();
                        }
                        break;
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TestNetInterruptRpt : AssemblyCommon.IProtoMessage
    {
        public void Encode(Google.Protobuf.CodedOutputStream writer)
        {
        }
        public void Decode(Google.Protobuf.CodedInputStream reader)
        {
            uint tag;
            while ((tag = reader.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        {
                            reader.SkipLastField();
                        }
                        break;
                }
            }
        }
    }

}

public class ILRuntime_CLGT
{
    static ILRuntime_CLGT()
    {

        //Initlize();

    }
    public static void Initlize()
    {

        ProtoBuf.PType.RegisterType("CLGT.HandReq", typeof(CLGT.HandReq));
        ProtoBuf.PType.RegisterType("CLGT.HandAck", typeof(CLGT.HandAck));
        ProtoBuf.PType.RegisterType("CLGT.DisconnectNtf", typeof(CLGT.DisconnectNtf));
        ProtoBuf.PType.RegisterType("CLGT.ItemInfo", typeof(CLGT.ItemInfo));
        ProtoBuf.PType.RegisterType("CLGT.LoginReq", typeof(CLGT.LoginReq));
        ProtoBuf.PType.RegisterType("CLGT.LoginAck", typeof(CLGT.LoginAck));
        ProtoBuf.PType.RegisterType("CLGT.AccessServiceReq", typeof(CLGT.AccessServiceReq));
        ProtoBuf.PType.RegisterType("CLGT.AccessServiceAck", typeof(CLGT.AccessServiceAck));
        ProtoBuf.PType.RegisterType("CLGT.KeepAliveReq", typeof(CLGT.KeepAliveReq));
        ProtoBuf.PType.RegisterType("CLGT.KeepAliveAck", typeof(CLGT.KeepAliveAck));
        ProtoBuf.PType.RegisterType("CLGT.TestNetInterruptRpt", typeof(CLGT.TestNetInterruptRpt));

    }
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
